
language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.6
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly
    - julia: 1.0
    - julia: 1.1

jobs:
  include:
    - stage: "Documentation"
      julia: 1.6
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
