name: format-check
on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - uses: actions/checkout@v1
      - name: Install JuliaFormatter and format
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.add(PackageSpec(name="JuliaFormatter"))
          using JuliaFormatter
          format("src", verbose=true)
          format("test", verbose=true)
      - name: Format check
        shell: julia --color=yes {0}
        run: |
          out = Cmd(`git diff --name-only`) |> read |> String
          if isempty(out)
              exit(0)
          else
            @error "Some files have not been formatted !!!"
            write(stdout, out)
            exit(1)
          end
